MODELS_DIR: "/home/econser/research/actove_refer/models/definitions/"
TRAIN:
  HAS_RPN: True
  USE_FLIPPED: False
  IMS_PER_BATCH: 1
  BBOX_NORMALIZE_TARGETS_PRECOMPUTED: True
  RPN_POSITIVE_OVERLAP: 0.7
  RPN_BATCHSIZE: 256
  PROPOSAL_METHOD: gt
  BG_THRESH_LO: 0.0
TEST:
  HAS_RPN: True